language: php
php:
  - 7.0
  - 7.1
  - 7.2

services:
  - redis-server

before_script:
  - echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - phpenv rehash

script:
  - vendor/bin/phpunit --verbose --colors
